ncuses-6.3 changes handling of the mvwprintw function and causes errors during build in fedora 37:
lpd/lp_diag.c: In function 'UI_help':
lpd/lp_diag.c:656:17: error: format not a string literal and no format arguments [-Werror=format-security]
  656 |                 mvwprintw(my_text_win, 0, 0, help1);
      |                 ^~~~~~~~~
lpd/lp_diag.c:658:17: error: format not a string literal and no format arguments [-Werror=format-security]
  658 |                 mvwprintw(my_text_win, 0, 0, help2);
      |                 ^~~~~~~~~
lpd/lp_diag.c:660:17: error: format not a string literal and no format arguments [-Werror=format-security]
  660 |                 mvwprintw(my_text_win, 0, 0, help3);
      |                 ^~~~~~~~~
lpd/lp_diag.c: In function 'startup_window':
lpd/lp_diag.c:1130:9: error: format not a string literal and no format arguments [-Werror=format-security]
 1130 |         mvprintw(2, 0, msg1);
      |         ^~~~~~~~
lpd/lp_diag.c:1131:9: error: format not a string literal and no format arguments [-Werror=format-security]
 1131 |         mvprintw(5, 0, msg2);
      |         ^~~~~~~~

Let's wrap all the missing places with "%s" format.

Signed-off-by: Than Ngo <than@redhat.com>